// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSt8KGuTyYYpRr9c5NX601X17mtLlm2Ao',
    appId: '1:109819209780:web:48ab48020505cd65e58261',
    messagingSenderId: '109819209780',
    projectId: 'dokkan-5212e',
    authDomain: 'dokkan-5212e.firebaseapp.com',
    storageBucket: 'dokkan-5212e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYTCoSy8-N8b4lq2k78NL_as-aY3OhpTo',
    appId: '1:109819209780:android:e20b3d8547b519bde58261',
    messagingSenderId: '109819209780',
    projectId: 'dokkan-5212e',
    storageBucket: 'dokkan-5212e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNL-IpN1XTHqwWdgj4qj8hEV0qP9lwq_A',
    appId: '1:109819209780:ios:4bd4671e2af9ba55e58261',
    messagingSenderId: '109819209780',
    projectId: 'dokkan-5212e',
    storageBucket: 'dokkan-5212e.appspot.com',
    iosBundleId: 'com.example.dokkanFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNL-IpN1XTHqwWdgj4qj8hEV0qP9lwq_A',
    appId: '1:109819209780:ios:d058c385ded964ede58261',
    messagingSenderId: '109819209780',
    projectId: 'dokkan-5212e',
    storageBucket: 'dokkan-5212e.appspot.com',
    iosBundleId: 'com.example.dokkanFirebase.RunnerTests',
  );
}
